common: 
  upload_file_name: 'data.csv'
  upload_directory: './upload'
#  upload_type: 'allcolumns'
efficient_frontier:
  points_number: 30
  default_riskfree: 0.04
  default_datasource: 'morningstar'
  override_datasource: true
downloader_morningstar:
  datasource:   'morningstar'
  symbolColumn: 'Symbol'
  dateColumn:   'Date'
  priceColumn:  'Close'
  directory:    'downloads'

downloader:
#  activesource:   'converter_tiingo'
  activesource:   'tiingo'
#  activesource:   'converter_asxhist'
#  activesource:   'marketindex'
  dateFormat:     '%Y-%m-%d'
  startDate:      '2010-11-25'
#  endDate:        '2019-06-28'
#  startDate:      '2010-12-31'
  endDate:        '2019-11-25'
#  symbols for quick test:        'AAPL,GOOGL,GOOG'
#  symbols excluded on purpose:        'IEF,'
  # global stocks:
#  symbols:        'AAPL,GOOGL,GOOG,MSFT,AMZN,FB,INTC,CSCO,CMCSA,PEP,AMGN,NVDA,TXN,AVGO,GILD,QCOM,KHC,PYPL,PCLN,ADBE,NFLX,CHTR,CELG,COST,SBUX,WBA,BIIB,BIDU,AABA,MDLZ,QQQ,AMAT,AMOV,TSLA,TMUS,MU,ADP,CSX,CME,MAR,ATVI,ISRG,ESRX,REGN,CTSH,EBAY,INTU,JD,NXPI,VRTX,MNST,EQIX,EA,ADI,ILMN,LRCX,ROST,LBTYA,LBTYB,AMTD,LBTYK,ALXN,FISV,PCAR,NTES,DLTR,TROW,AAL,PAYX,WDC,IBKR,XEL,ADSK,SIRI,MYL,DISH,CERN,NTRS,WDAY,HBANO,VCSH,ORLY,FITB,MCHP,CTRP,INCY,PFG,WLTW,SBAC,EXPE,VCIT,ALGN,SWKS,INFO,DVY,SYMC,PFF,CHKP,XLNX,CTAS,KLAC,WYNN,LBRDK,LBRDA,BMRN,HBAN,VRSK,FAST,XRAY,NTAP,MXIM,ULTA,VOD,MELI,IDXX,CA,CBOE,VIA,ETFC,CTXS,ALNY,LSXMK,TTWO,SNPS,NDAQ,ASML,ANSS,LKQ,JBHT,FANG,NCLH,IPGP,SIVB,CHRW,SPLK,STX,EMB,CDNS,HOLX,CINF,MBB,SHPG,TEAM,ACGL,EXPD,CSJ,HAS,SEIC,MRVL,HSIC,GRMN,SHY,SNI,AKAM,AMD,YNDX,CSGP,ODFL,CGNX,CDW,VRSN,IAC,QVCA,RYAAY,STLD,SCZ,LULU,TRMB,VXUS,QVCB,VIAB,IBB,ZION,CPRT,NWS,FLEX,CDK,ON,NWSA,DOX,TSCO,EXEL,IEP,OTEX,DISCB,NKTR,AGNCB,JKHY,ACWI,EWBC,CZR,MTCH,QRVO,ABMD,NDSN,ALKS,DISCA,IXUS,OLED,SSNC,FFIV,JAZZ,BLUE,SGEN,DISCK,Z,ZG,BNDX,CG,SHV,FWONK,GT,SINA,FTNT,GLPI,SBNY,CIU,AGNC,MIDD,MKTX,PPC,WB,UHAL,COHR,HDS,NBIX,FSLR,COMM,QGEN'

  # S&P 100
  symbols:        'AAPL,ABBV,ABT,ACN,ADBE,AGN,AIG,ALL,AMGN,AMZN,AXP,BA,BAC,BIIB,BK,BKNG,BLK,BMY,BRK.B,C,CAT,CELG,CHTR,CL,CMCSA,COF,COP,COST,CSCO,CVS,CVX,DD,DHR,DIS,DOW,DUK,EMR,EXC,F,FB,FDX,GD,GE,GILD,GM,GOOG,GOOGL,GS,HD,HON,IBM,INTC,JNJ,JPM,KHC,KMI,KO,LLY,LMT,LOW,MA,MCD,MDLZ,MDT,MET,MMM,MO,MRK,MS,MSFT,NEE,NFLX,NKE,NVDA,ORCL,OXY,PEP,PFE,PG,PM,PYPL,QCOM,RTN,SBUX,SLB,SO,SPG,T,TGT,TXN,UNH,UNP,UPS,USB,UTX,V,VZ,WBA,WFC,WMT,XOM'

  # S&P 500
#  symbols:        'MMM,AOS,ABT,ABBV,ACN,ATVI,AYI,ADBE,AAP,AMD,AES,AET,AMG,AFL,A,APD,AKAM,ALK,ALB,ARE,ALXN,ALGN,ALLE,AGN,ADS,LNT,ALL,GOOGL,GOOG,MO,AMZN,AEE,AAL,AEP,AXP,AIG,AMT,AWK,AMP,ABC,AME,AMGN,APH,APC,ADI,ANDV,ANSS,ANTM,AON,APA,AIV,AAPL,AMAT,APTV,ADM,ARNC,AJG,AIZ,T,ADSK,ADP,AZO,AVB,AVY,BHGE,BLL,BAC,BAX,BBT,BDX,BRK.B,BBY,BIIB,BLK,HRB,BA,BKNG,BWA,BXP,BSX,BHF,BMY,AVGO,BF.B,CHRW,CA,COG,CDNS,CPB,COF,CAH,KMX,CCL,CAT,CBOE,CBRE,CBS,CELG,CNC,CNP,CTL,CERN,CF,SCHW,CHTR,CVX,CMG,CB,CHD,CI,XEC,CINF,CTAS,CSCO,C,CFG,CTXS,CME,CMS,KO,CTSH,CL,CMCSA,CMA,CAG,CXO,COP,ED,STZ,GLW,COST,COTY,CCI,CSRA,CSX,CMI,CVS,DHI,DHR,DRI,DVA,DE,DAL,XRAY,DVN,DLR,DFS,DISCA,DISCK,DISH,DG,DLTR,D,DOV,DWDP,DPS,DTE,DUK,DRE,DXC,ETFC,EMN,ETN,EBAY,ECL,EIX,EW,EA,EMR,ETR,EVHC,EOG,EQT,EFX,EQIX,EQR,ESS,EL,RE,ES,EXC,EXPE,EXPD,ESRX,EXR,XOM,FFIV,FB,FAST,FRT,FDX,FIS,FITB,FE,FISV,FLIR,FLS,FLR,FMC,FL,F,FTV,FBHS,BEN,FCX,GPS,GRMN,IT,GD,GE,GGP,GIS,GM,GPC,GILD,GPN,GS,GT,GWW,HAL,HBI,HOG,HRS,HIG,HAS,HCA,HCP,HP,HSIC,HES,HPE,HLT,HOLX,HD,HON,HRL,HST,HPQ,HUM,HBAN,HII,IDXX,INFO,ITW,ILMN,INCY,IR,INTC,ICE,IBM,IP,IPG,IFF,INTU,ISRG,IVZ,IPGP,IQV,IRM,JBHT,JEC,SJM,JNJ,JCI,JPM,JNPR,KSU,K,KEY,KMB,KIM,KMI,KLAC,KSS,KHC,KR,LB,LLL,LH,LRCX,LEG,LEN,LUK,LLY,LNC,LKQ,LMT,L,LOW,LYB,MTB,MAC,M,MRO,MPC,MAR,MMC,MLM,MAS,MA,MAT,MKC,MCD,MCK,MDT,MRK,MET,MTD,MGM,KORS,MCHP,MU,MSFT,MAA,MHK,TAP,MDLZ,MON,MNST,MCO,MS,MSI,MYL,NDAQ,NOV,NAVI,NKTR,NTAP,NFLX,NWL,NFX,NEM,NWSA,NWS,NEE,NLSN,NKE,NI,NBL,JWN,NSC,NTRS,NOC,NCLH,NRG,NUE,NVDA,ORLY,OXY,OMC,OKE,ORCL,PCAR,PKG,PH,PAYX,PYPL,PNR,PBCT,PEP,PKI,PRGO,PFE,PCG,PM,PSX,PNW,PXD,PNC,RL,PPG,PPL,PX,PFG,PG,PGR,PLD,PRU,PEG,PSA,PHM,PVH,QRVO,QCOM,PWR,DGX,RRC,RJF,RTN,O,RHT,REG,REGN,RF,RSG,RMD,RHI,ROK,COL,ROP,ROST,RCL,SPGI,CRM,SBAC,SCG,SLB,STX,SEE,SRE,SHW,SPG,SWKS,SLG,SNA,SO,LUV,SWK,SBUX,STT,SRCL,SYK,STI,SIVB,SYMC,SYF,SNPS,SYY,TROW,TTWO,TPR,TGT,TEL,FTI,TXN,TXT,BK,CLX,COO,HSY,MOS,TRV,DIS,TMO,TIF,TWX,TJX,TMK,TSS,TSCO,TDG,TRIP,FOXA,FOX,TSN,USB,UDR,ULTA,UAA,UA,UNP,UAL,UNH,UPS,URI,UTX,UHS,UNM,VFC,VLO,VAR,VTR,VRSN,VRSK,VZ,VRTX,VIAB,V,VNO,VMC,WMT,WBA,WM,WAT,WEC,WFC,WELL,WDC,WU,WRK,WY,WHR,WMB,WLTW,WYN,WYNN,XEL,XRX,XLNX,XL,XYL,YUM,ZBH,ZION,ZTS'
#  symbols:        'A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AET,AFL,AGN,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMD,AME,AMG,AMGN,AMP,AMT,AMZN,ANDV,ANSS,ANTM,AON,AOS,APA,APC,APD,APH,APTV,ARE,ARNC,ATVI,AVB,AVGO,AVY,AWK,AXP,AYI,AZO,BA,BAC,BAX,BBT,BBY,BDX,BEN,BF.B,BHF,BIIB,BKNG,BLK,BLL,BMY,BSX,BWA,BXP,C,CA,CAG,CAH,CAT,CB,CBOE,CBRE,CBS,CCI,CCL,CDNS,CELG,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CINF,CL,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COP,COST,COTY,CPB,CSCO,CSRA,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,DE,DFS,DG,DHI,DHR,DISCA,DISCK,DISH,DLR,DLTR,DOV,DPS,DRE,DRI,DTE,DUK,DVA,DVN,DXC,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,EQT,ES,ESRX,ESS,ETFC,ETN,ETR,EVHC,EW,EXC,EXPD,EXPE,EXR,F,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FL,FLIR,FLR,FLS,FMC,FRT,FTV,GD,GE,GGP,GILD,GIS,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GT,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HIG,HII,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HSIC,HST,HUM,IBM,ICE,IDXX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,JBHT,JCI,JEC,JNJ,JNPR,JPM,JWN,K,KEY,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LEG,LEN,LH,LKQ,LLL,LLY,LMT,LNC,LNT,LOW,LRCX,LUK,LYB,M,MA,MAA,MAC,MAR,MAS,MAT,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MLM,MMC,MMM,MNST,MO,MON,MPC,MRK,MRO,MS,MSFT,MSI,MTB,MTD,MU,MYL,NAVI,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NFX,NI,NKE,NKTR,NLSN,NOC,NOV,NRG,NSC,NTAP,NTRS,NUE,NVDA,NWL,NWS,NWSA,OKE,OMC,ORCL,ORLY,OXY,PAYX,PBCT,PCAR,PCG,PEP,PFE,PFG,PH,PKG,PKI,PM,PNR,PRGO,PYPL,QCOM,QRVO,RE,SCHW,SJM,SNPS,STZ,T,TAP,TROW,TSCO,TTWO,TXN,ULTA,VIAB,VRSK,VRSN,VRTX,WBA,XEC,XOM,XRAY'
#  symbols breaking download:        'FSLR,COMM,FOX,FOXA,'
  # asx symbols:
#  symbols:  'ASX:ABP,ASX:AX1,ASX:ABC,ASX:APT,ASX:AGL,ASX:AQG,ASX:ALQ,ASX:ALU,ASX:AWC,ASX:AMA,ASX:AYS,ASX:AMC,ASX:AMP,ASX:ANN,ASX:ANZ,ASX:APE,ASX:APA,ASX:ADI,ASX:APX,ASX:ARB,ASX:ALG,ASX:ARF,ASX:ALL,ASX:AHY,ASX:ASX,ASX:ALX,ASX:AUB,ASX:AIA,ASX:AD8,ASX:AMI,ASX:AZJ,ASX:ASL,ASX:AST,ASX:ASB,ASX:AAC,ASX:API,ASX:AVN,ASX:AOG,ASX:AVH,ASX:BBN,ASX:BOQ,ASX:BAP,ASX:BPT,ASX:BGA,ASX:BAL,ASX:BGL,ASX:BEN,ASX:BHP,ASX:BIN,ASX:BKL,ASX:BSL,ASX:BLD,ASX:BXB,ASX:BVS,ASX:BRG,ASX:BKW,ASX:BUB,ASX:BWP,ASX:BWX,ASX:CTX,ASX:CDD,ASX:CVN,ASX:CAR,ASX:CWP,ASX:CNI,ASX:CIP,ASX:CMA,ASX:CGF,ASX:CIA,ASX:CHC,ASX:CQR,ASX:CQE,ASX:CNU,ASX:CLW,ASX:CIM,ASX:CWY,ASX:CUV,ASX:CCL,ASX:COH,ASX:CDA,ASX:COL,ASX:CKF,ASX:CBA,ASX:CPU,ASX:COE,ASX:CTD,ASX:CGC,ASX:CCP,ASX:CMW,ASX:CWN,ASX:CSL,ASX:CSR,ASX:CYB,ASX:DCN,ASX:DTL,ASX:DXS,ASX:DHG,ASX:DMP,ASX:DOW,ASX:ECX,ASX:A2M,ASX:EHE,ASX:EHL,ASX:ELD,ASX:EML,ASX:EPW,ASX:EVN,ASX:FAR,ASX:FBU,ASX:FLT,ASX:FMG,ASX:FNP,ASX:FPH,ASX:FXL,ASX:GDI,ASX:GEM,ASX:GMA,ASX:GMG,ASX:GNC,ASX:GOR,ASX:GOZ,ASX:GPT,ASX:GUD,ASX:GWA,ASX:GXY,ASX:HLS,ASX:HPI,ASX:HSN,ASX:HT1,ASX:HUB,ASX:HVN,ASX:IAG,ASX:IAP,ASX:IEL,ASX:IFL,ASX:IFM,ASX:IFN,ASX:IGL,ASX:IGO,ASX:ILU,ASX:IMD,ASX:IMF,ASX:INA,ASX:ING,ASX:INR,ASX:IPH,ASX:IPL,ASX:IRE,ASX:IRI,ASX:ISX,ASX:IVC,ASX:JBH,ASX:JHC,ASX:JHG,ASX:JHX,ASX:JIN,ASX:JMS,ASX:KAR,ASX:KGN,ASX:LIC,ASX:LLC,ASX:LNK,ASX:LOV,ASX:LYC,ASX:MAH,ASX:MFG,ASX:MGR,ASX:MGX,ASX:MIN,ASX:MLD,ASX:MMS,ASX:MND,ASX:MNY,ASX:MP1,ASX:MPL,ASX:MQG,ASX:MSB,ASX:MTS,ASX:MVF,ASX:MYR,ASX:MYS,ASX:MYX,ASX:NAB,ASX:NAN,ASX:NCK,ASX:NCM,ASX:NCZ,ASX:NEA,ASX:NEC,ASX:NGI,ASX:NHC,ASX:NHF,ASX:NIC,ASX:NSR,ASX:NST,ASX:NUF,ASX:NWH,ASX:NWL,ASX:NWS,ASX:NXT,ASX:OFX,ASX:OGC,ASX:OML,ASX:ORA,ASX:ORE,ASX:ORG,ASX:ORI,ASX:OSH,ASX:OZL,ASX:PDL,ASX:PDN,ASX:PET,ASX:PGH,ASX:PLS,ASX:PME,ASX:PMV,ASX:PNI,ASX:PNV,ASX:PPT,ASX:PRU,ASX:PTM,ASX:QAN,ASX:QBE,ASX:QUB,ASX:RDC,ASX:REA,ASX:REG,ASX:RFF,ASX:RHC,ASX:RIO,ASX:RMD,ASX:RMS,ASX:RRL,ASX:RSG,ASX:RWC,ASX:S32,ASX:SAR,ASX:SBM,ASX:SCG,ASX:SCP,ASX:SDA,ASX:SDF,ASX:SEA,ASX:SEK,ASX:SFR,ASX:SGF,ASX:SGM,ASX:SGP,ASX:SGR,ASX:SHL,ASX:SHV,ASX:SIG,ASX:SIQ,ASX:SKC,ASX:SKI,ASX:SLC,ASX:SLR,ASX:SM1,ASX:SOL,ASX:SPK,ASX:SPL,ASX:SSM,ASX:STO,ASX:SUL,ASX:SUN,ASX:SVW,ASX:SWM,ASX:SXL,ASX:SXY,ASX:SYD,ASX:SYR,ASX:TAH,ASX:TCL,ASX:TGR,ASX:TLS,ASX:TNE,ASX:TPM,ASX:TWE,ASX:URW,ASX:VCX,ASX:VEA,ASX:VLW,ASX:VOC,ASX:VRL,ASX:VRT,ASX:VVR,ASX:WAF,ASX:WBC,ASX:WEB,ASX:WES,ASX:WGX,ASX:WHC,ASX:WOR,ASX:WOW,ASX:WPL,ASX:WPP,ASX:WSA,ASX:WTC,ASX:XRO,ASX:Z1P'

downloaders:
  tiingo:
    datasource:   'tiingo'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y-%m-%d'
    priceColumn:  'close'
    directory:    'downloads'
    inputfilename: 'upload/a.txt'
    access_key:   'b52aff4cd1d604991702bf6bec5151924323ac4a'
  quandl:
    datasource:   'quandl'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y%m%d'
    priceColumn:  'adjClose'
    directory:    'downloads'
    inputfilename: 'upload/a.txt'
    access_key:   'KtxeUhoJZDsmvsmhVsWf'
  marketdata:
    datasource:   'marketdata'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y%m%d'
    priceColumn:  'adjClose'
    inputfilename: 'upload/a.txt'
    directory:    'downloads'
    access_key:   ''
  converter_invest:
    datasource:   'converter_invest'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%b %d, %Y'
    priceColumn:  'close'
    directory:    'downloads'
    inputfilename: 'upload/b.txt'
    access_key:   ''
  converter_asxhist:
    datasource:   'converter_asxhist'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y%m%d'
    priceColumn:  'close'
    directory:    'downloads'
    inputfilename: 'floatdatadownload/b.txt'
    access_key:   ''
  converter_tiingo:
    datasource:   'converter_tiingo'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y-%m-%d'
    priceColumn:  'close'
    directory:    'downloads'
  marketindex:
    datasource:   'marketindex'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y%m%d'
    priceColumn:  'close'
    directory:    'downloads'
    access_key:   ''
